### ISSUE TITLE
Implementing horovod in DALLE-pytorch

### ISSUE THREAD

**Issue by afiaka87** [kobiso/DALLE-reproduction#1]
@janEbert @kobiso 

Hey! You've been doing fantastic work with these early training examples. It's very helpful to us.

I'm not sure if you're certain but we're working with some amazing researchers from Helmholtz currently. They have access to the JULICH super-computer and would like to help us train and publish a decent model. They're generously allowing us allocated time to use their compute should we need to run experiments and make fixes to the codebase.

Would you be interested in helping us to implement horovod in the DALLE-pytorch main branch? I've been told you're more than welcome to join us on the JULICH compute if that's helpful.

**Comment by janEbert** [comment]
Hey @kobiso! I've uploaded a branch with Horovod support (it still needs some API cleanup so expect force pushes) at https://github.com/janEbert/DALLE-pytorch/tree/horovod.
Are you allowed to share the BPE-related code with us?

**Comment by kobiso** [comment]
@afiaka87 I would love to help improve DALLE model. But i might be not active as much as you folks because of workload from my work @_@. I will try my best to be helpful.

@janEbert Sure, I will PR it soon :)

**Comment by afiaka87** [comment]
> @afiaka87 I would love to help improve DALLE model. But i might be not active as much as you folks because of workload from my work @_@. I will try my best to be helpful.
> 
> @janEbert Sure, I will PR it soon :)

Of course! A good work/life balance is crucial. You've done plenty as is so it's all appreciated.

**Comment by janEbert** [comment]
Hahaha, yeah, take all the time you need! Congratulations on all the results and thanks for taking the time for this in the first place. :)
I've also heavily cleaned up the branch and submitted the PR to lucidrains'.
