### ISSUE TITLE
How can I use Deepspeed Sparse Attention?

### ISSUE THREAD

**Issue by wcshin-git** [kobiso/DALLE-reproduction#6]
I just installed Deepspeed well.
![image](https://user-images.githubusercontent.com/76698585/117978178-9013f900-b36c-11eb-9bb9-44f6bc22ddf5.png)

And then the next step is same as usual? 
I mean, just change the `--attn_types` arguments
and 
run the command like this?
`python train_dalle.py --vae_path ./vae.pt --image_text_folder /path/to/data --attn_types full,sparse`
Or do I have to run the command line like this?
`deepspeed train_dalle.py [args...] --deepspeed`

**Comment by kobiso** [comment]
If this is a question about dalle-pytorch repo, both are correct.
The first command is training a model in a single gpu, and the second one is for training with Deepspeed DDP.

**Comment by wcshin-git** [comment]
Ah, I see :) Thank you for your reply.
